import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import productcategories from '../data/productcategories.json'
import Popup from '../components/Popup'
import { useState } from 'react'

export default function Home() {
  console.log(productcategories)
  const [popup, setPopup] = useState(null)
  return (
    <div className={styles.container}>
      <Head>
        <title>Attensi Frontend Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {productcategories.map((category) => (
          <div key={category.id} style={{ width: '70%', minWidth: '320px' }}>
            <h2>{category.title}</h2>
            <div className="category-container">
              {category.products.map((product) => (
                <div
                  className="product"
                  onClick={() => setPopup(product)}
                  key={product.id}
                >
                  <img
                    style={{
                      height: 'fit-content',
                      width: '90%',
                      margin: 'auto',
                    }}
                    src={product.image}
                  />
                  <div>{product.title}</div>
                  <div>{product.type}</div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </main>
      <Popup data={popup} setPopup={setPopup}></Popup>
    </div>
  )
}
